export const rules={
  name:[
    {
      required:true,
      message:'用户名不能为空',
      trigger:'blur'
    },
    {
      min:5,
      max:10,
      message:'用户名的长度为5-10个字符',
      trigger:'blur'
    }
  ],
  phone:[
    {
      required:true,
      message:'手机号不能为空',
      trigger:'blur'
    },
    {
      type:'number',
      message:'手机号的长度最多为11个数字',
      trigger:'blur'
    }
  ],
  password:[
    {
      required:true,
      message:'密码不能为空',
      trigger:'blur'
    },
    {
      min:3,
      message:'密码的长度为3个字符以上',
      trigger:'blur'
    }
  ]
}
