// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElLinks: typeof import('element-plus/es')['ElLinks']
  const ElPhone: typeof import('element-plus/es')['ElPhone']
  const ElResult: typeof import('element-plus/es')['ElResult']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
