import type {IForm} from '../../../../../base-ui/form/types'
export const searchFormConfig:IForm={
  labelWidth:'120px',
  itemLayout:{
    padding:'10px 40px'
  },
  formItems:[
    {
      field:'name',
      type:'input',
      label:'姓名',
      placeholder:'请输入姓名'
    },
    {
      field:'realname',
      type:'input',
      label:'真实姓名',
      placeholder:'请输入真实姓名'
    },
    {
      field:'phone',
      label:'手机号码',
      type:'input',
      placeholder:"请输入手机号码"
    },
    {
      field:'status',
      type:'select',
      label:'状态',
      options:[
        {title:'启用',value:'1'},
        {title:'禁用',value:'0'}
      ]
    },
    {
      field:'createTime',
      type:'datepicker',
      label:'创建时间',
      otherOptions:{
        startPlaceholder:'开始时间',
        endPlaceholder:'结束时间',
        type:'daterange'
      }
    }
  ]
}
